eveltic_cookie:
    categories:
        - { name: 'technical', required: true }
        - { name: 'preferences', required: false }
        - { name: 'analytics', required: false }
        - { name: 'ads', required: false }
    domain: null
    version: 1
    theme_mode: 'auto'
    expiration: '+2 years'
