sonata_admin:
    title: '%project_title% Admin'
    persist_filters: true
    show_mosaic_button: false
    search: false
    options:
#        skin: 'skin-green'
        form_type: 'standard'
        default_icon: 'fas fa-folder'
        logo_content: 'icon'
        list_action_button_content: 'icon'
        html5_validate: true
        confirm_exit: true
        use_select2: true
        use_icheck: true
        pager_links: 10
    security:
        handler: 'sonata.admin.security.handler.role'
        role_admin: 'ROLE_ADMIN'
        role_super_admin: 'ROLE_SUPER_ADMIN'
    templates:
        layout: 'admin/layout.html.twig'
    dashboard:
        blocks:
            - { type: 'sonata.admin.block.admin_list', position: 'left' }

when@dev:
    sonata_admin:
        options:
            use_bootlint: true
            js_debug: true
        dashboard:
            groups:
                Web:
                    keep_open: true
