stof_doctrine_extensions:
    default_locale: '%default_locale%'
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            softdeleteable: false
            sortable: false
            tree: false

