twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates': 'App'
        '%kernel.project_dir%/assets/styles': 'styles'
        '%kernel.project_dir%/assets/images': 'images'
    form_themes:
        - 'tailwind_2_layout.html.twig'
        - '@App/form_templates/vich_uploader_form_fields.html.twig'
        - '@App/form_templates/adapted_a2lix_translation_form.html.twig'
    globals:
        google_tag_manager_enabled: false
        #google_tag_manager_api_key: '%env(string:GOOGLE_TAG_MANAGER_ACCOUNT)%'
        short_project_title: '%short_project_title%'
        project_title: '%project_title%'
        admin_tag_version: '%admin_tag_version%'
        customer_name: '%env(string:CUSTOMER_NAME)%'
        customer_url: '%env(string:CUSTOMER_URL)%'
        facebook_url: '%env(string:FACEBOOK_URL)%'
        instagram_url: '%env(string:INSTAGRAM_URL)%'
        youtube_url: '%env(string:YOUTUBE_URL)%'
        developer_name: '%env(string:DEVELOPER_NAME)%'
        developer_url: '%env(string:DEVELOPER_URL)%'

when@test:
    twig:
        strict_variables: true
