vich_uploader:
    db_driver: 'orm'
    metadata:
        type: 'attribute'
    mappings:
        customers:
            uri_prefix: '/images/customers'
            upload_destination: '%kernel.project_dir%/public/images/customers'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        projects:
            uri_prefix: '/images/projects'
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        images:
            uri_prefix: '/images/projects'
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        services:
            uri_prefix: '/images/services'
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        documents:
            uri_prefix: '/documents/projects'
            upload_destination: '%kernel.project_dir%/public/documents/projects'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        expenses:
            uri_prefix: '/uploads/expenses'
            upload_destination: '%kernel.project_dir%/var/uploads/expenses'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
