server {
    listen 80;
    listen [::]:80;

    client_max_body_size 100M;

    server_name stage.boxidiomes.cat;
    root /var/www/andrea-dog-coach/public/;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 128;
    gzip_types    text/plain application/javascript application/x-javascript text/javascript text/xml text/css text/html application/json  application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;


    location / {
        # try to serve file directly, fallback to app.php
        # replace app.php with app_dev.php in dev
        try_files $uri /index.php$is_args$args;
    }

    add_header Access-Control-Allow-Origin "*";
    add_header Access-Control-Allow-Headers "*";

    location ~ ^/index\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/andrea_dog_coach_4_error.log;
    access_log /var/log/nginx/andrea_dog_coach_4_access.log;
}
