imports:
    - { resource: 'admins.yaml' }

parameters:
    default_locale: 'ca'
    short_project_title: 'ADC'
    project_title: 'Andrea Dog Coach'
    customer_delivery_address: '%env(string:CUSTOMER_DELIVERY_ADDRESS)%'
    admin_tag_version: '100000'
    admin_password: '%env(string:ADMIN_PASSWORD)%'
    delivery_dev_address: '%env(string:DEV_DELIVERY_ADDRESS)%'
    locale_i18n: [ 'es', 'en', 'de' ]
    locale_i18n_full: [ 'ca', 'es', 'en', 'de' ]
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            '$kpd': '%kernel.project_dir%'
            '$locale': '%default_locale%'
            '$locales': '%locale_i18n_full%'
    App\:
        resource: '../src/'
    # Events
    App\Form\EventListener\DefaultTranslationsListener:
        arguments:
            - '@App\Form\Translation\GedmoTranslationForm'
    App\Form\EventListener\GedmoTranslationsListener:
        arguments:
            - '@App\Form\Translation\GedmoTranslationForm'
    App\Form\Translation\DefaultTranslationForm:
        arguments:
            - '@form.registry'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
    App\Form\Translation\GedmoTranslationForm:
        arguments:
            - '@form.registry'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
        calls:
            - setGedmoTranslatableListener: [ '@stof_doctrine_extensions.listener.translatable' ]
    App\Event\Subscriber\SitemapEventSubscriber:
        arguments:
            - '@router'
            - '@App\Repository\ServiceRepository'
        tags:
            - { name: 'kernel.event_subscriber', priority: 100 }
    # Forms
    App\Form\Type\GedmoTranslationsType:
        arguments:
            - '@App\Form\EventListener\GedmoTranslationsListener'
            - '@App\Form\Translation\GedmoTranslationForm'
            - '%locale_i18n%'
            - ~
        tags:
            - { name: 'form.type' }
    App\Form\Type\TranslationsFormsType:
        arguments:
            - '%locale_i18n%'
            - ~
        tags:
            - { name: 'form.type' }
