parameters:
    default_locale: 'ca'
    locale_i18n: [ 'es', 'en' ]
    locale_i18n_full: [ 'ca', 'es', 'en' ]

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
